# Setup
title: Jeongmin Han
description: Welcome to my blog.
myphoto: /images/me.jpg
paginate: 5
permalink: pretty
cover_image: /images/bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Jeongmin Han
  url: https://github.com/hjm6021/
  email: hjm6021@gmail.com
